# Generated by Django 4.1.7 on 2023-02-27 17:24

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=9)),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyList',
            fields=[
                ('fullName', models.TextField(primary_key=True, serialize=False)),
                ('shortForm', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmitted',
            fields=[
                ('formID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('control_no', models.TextField()),
                ('applied_by', models.TextField()),
                ('currency_desc', models.IntegerField()),
                ('purpose', models.TextField()),
                ('date_of_requirement', models.DateField()),
                ('date_of_return', models.DateField()),
                ('state', models.IntegerField()),
                ('approved_by', models.TextField()),
                ('finalized_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversions',
            fields=[
                ('convID', models.AutoField(primary_key=True, serialize=False)),
                ('denomination', models.IntegerField()),
                ('no_of_pcs', models.FloatField()),
                ('value_in_local', models.FloatField()),
                ('formID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.formsubmitted')),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversions',
            constraint=models.UniqueConstraint(fields=('convID', 'formID'), name='unique_convID_formID_combination'),
        ),
    ]
