# Generated by Django 4.1.7 on 2023-02-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmitted',
            name='currency_desc',
            field=models.TextField(),
        ),
    ]
