# Generated by Django 4.1.7 on 2023-03-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_conversions_denomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversions',
            name='currency',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversions',
            name='denomination',
            field=models.IntegerField(),
        ),
    ]
