# Generated by Django 4.1.7 on 2023-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_formsubmitted_declined_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmitted',
            name='declined_by',
            field=models.TextField(default=-1),
        ),
    ]
