# Generated by Django 4.1.7 on 2023-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_formsubmitted_declined_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmitted',
            name='approved_by',
            field=models.TextField(default=-1),
        ),
        migrations.AlterField(
            model_name='formsubmitted',
            name='finalized_by',
            field=models.TextField(default=-1),
        ),
    ]
