# Generated by Django 4.1.7 on 2023-03-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_formsubmitted_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('formID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('orderNo', models.IntegerField()),
                ('currency_desc', models.TextField()),
                ('purpose', models.TextField()),
                ('source', models.TextField()),
                ('share', models.TextField()),
                ('date_of_requirement', models.DateField()),
                ('period', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Form2Conversions',
            fields=[
                ('convID', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.TextField()),
                ('denomination', models.IntegerField()),
                ('no_of_pcs', models.FloatField()),
                ('value_in_local', models.FloatField()),
                ('formID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.formsubmitted')),
            ],
        ),
        migrations.AddConstraint(
            model_name='form2conversions',
            constraint=models.UniqueConstraint(fields=('convID', 'formID'), name='unique_convID_formID_combination2'),
        ),
    ]
