# Generated by Django 4.1.7 on 2023-03-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_form2conversions_formid'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='state',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form2conversions',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
