# Generated by Django 4.1.7 on 2023-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_form2_state_form2conversions_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='control_no',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
