# Generated by Django 4.1.7 on 2023-03-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_form2_control_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='approved_by',
            field=models.TextField(default=-1),
        ),
        migrations.AddField(
            model_name='form2',
            name='declined_by',
            field=models.TextField(default=-1),
        ),
        migrations.AddField(
            model_name='form2',
            name='finalized_by',
            field=models.TextField(default=-1),
        ),
    ]
