# Generated by Django 4.1.7 on 2023-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_form2_approved_by_form2_declined_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencylist',
            name='amount',
            field=models.FloatField(default=100000),
            preserve_default=False,
        ),
    ]
