# Generated by Django 4.1.7 on 2023-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_form1submitted_returned_form2submitted_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1submitted',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='form1submitted',
            name='date_of_requirement',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='form2submitted',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
