# Generated by Django 4.1.7 on 2023-03-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_loghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1submitted',
            name='date_of_requirement',
            field=models.DateField(),
        ),
    ]
